#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: F_MED_BlackMonday_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MED_BlackMonday_AnimBP.F_MED_BlackMonday_AnimBP_C
// 0x0FC0 (0x16C0 - 0x0700)
class UF_MED_BlackMonday_AnimBP_C final : public UCustomCharacterPartAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0700(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0708(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0710(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0718(0x0020)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x0738(0x0150)(ContainsInstancedReference)
	uint8                                         Pad_888[0x8];                                      // 0x0888(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0890(0x0960)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x11F0(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x1210(0x0020)()
	struct FAnimNode_Constraint                   AnimGraphNode_Constraint;                          // 0x1230(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x1338(0x0128)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x1460(0x0128)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x1588(0x0128)()
	double                                        crouch_alpha;                                      // 0x16B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_F_MED_BlackMonday_AnimBP(int32 EntryPoint);
	void OnBeginCrouching();
	void OnEndCrouching();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_BlackMonday_AnimBP_C">();
	}
	static class UF_MED_BlackMonday_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_BlackMonday_AnimBP_C>();
	}
};

}

