#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: F_MED_ASN_Starfish_Head_01_AnimBP_Child

#include "Basic.hpp"

#include "F_MED_ASN_Starfish_Head_01_AnimBP_Child_classes.hpp"
#include "F_MED_ASN_Starfish_Head_01_AnimBP_Child_parameters.hpp"


namespace SDK
{

// Function F_MED_ASN_Starfish_Head_01_AnimBP_Child.F_MED_ASN_Starfish_Head_01_AnimBP_Child_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_MED_ASN_Starfish_Head_01_AnimBP_Child_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_MED_ASN_Starfish_Head_01_AnimBP_Child_C", "BlueprintUpdateAnimation");

	Params::F_MED_ASN_Starfish_Head_01_AnimBP_Child_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function F_MED_ASN_Starfish_Head_01_AnimBP_Child.F_MED_ASN_Starfish_Head_01_AnimBP_Child_C.ExecuteUbergraph_F_MED_ASN_Starfish_Head_01_AnimBP_Child
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_MED_ASN_Starfish_Head_01_AnimBP_Child_C::ExecuteUbergraph_F_MED_ASN_Starfish_Head_01_AnimBP_Child(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_MED_ASN_Starfish_Head_01_AnimBP_Child_C", "ExecuteUbergraph_F_MED_ASN_Starfish_Head_01_AnimBP_Child");

	Params::F_MED_ASN_Starfish_Head_01_AnimBP_Child_C_ExecuteUbergraph_F_MED_ASN_Starfish_Head_01_AnimBP_Child Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

