#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: F_MED_ASN_Starfish_Head_01_AnimBP_Child

#include "Basic.hpp"

#include "Fortnite_Base_Head_Export_Skeleton_AnimBP_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MED_ASN_Starfish_Head_01_AnimBP_Child.F_MED_ASN_Starfish_Head_01_AnimBP_Child_C
// 0x0010 (0x1F50 - 0x1F40)
class UF_MED_ASN_Starfish_Head_01_AnimBP_Child_C final : public UFortnite_Base_Head_Export_Skeleton_AnimBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_F_MED_ASN_Starfish_Head_01_AnimBP_Child_C; // 0x1F40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_F_MED_ASN_Starfish_Head_01_AnimBP_Child(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_ASN_Starfish_Head_01_AnimBP_Child_C">();
	}
	static class UF_MED_ASN_Starfish_Head_01_AnimBP_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_ASN_Starfish_Head_01_AnimBP_Child_C>();
	}
};

}

