#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FortCosmeticVariantItemTile_MP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortCosmeticVariantItemTile_MP.FortCosmeticVariantItemTile_MP_C
// 0x0020 (0x14B0 - 0x1490)
class UFortCosmeticVariantItemTile_MP_C final : public UCommonButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFortVariantItemVM*                     FortVariantItemVM;                                 // 0x1498(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UWBP_UIKit_CosmeticVariantItemTile_Base_C* WBP_UIKit_CosmeticVariantItemTile_Base;         // 0x14A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_OnEntryReleased();
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void ExecuteUbergraph_FortCosmeticVariantItemTile_MP(int32 EntryPoint);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void PreConstruct(bool IsDesignTime);
	void Set_Variant_Display_Info(const struct FVariantDisplayInfo& VariantDisplayInfo);
	void SetFortVariantItemVM(class UFortVariantItemVM* ViewModel);
	void SetImageMaterial(class UMaterialInterface* InMaterial);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortCosmeticVariantItemTile_MP_C">();
	}
	static class UFortCosmeticVariantItemTile_MP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCosmeticVariantItemTile_MP_C>();
	}
};

}

