#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: QualityLevelSelectTimer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass QualityLevelSelectTimer.QualityLevelSelectTimer_C
// 0x0018 (0x0340 - 0x0328)
class UQualityLevelSelectTimer_C final : public UFortHUDQualityLevelSelectTimer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        TextScaleUnderOneSecond;                           // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TextScaleOverOneSecond;                            // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QualityLevelSelectTimer(int32 EntryPoint);
	void OnInitialized();
	void OnProgressEnded();
	void OnProgressStarted(const float duration);
	void OnTimeRemainingChanged(const float TimeRemaining);
	void UpdateTextScale(double TimeRemaining);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"QualityLevelSelectTimer_C">();
	}
	static class UQualityLevelSelectTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQualityLevelSelectTimer_C>();
	}
};

}

