#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: TODM_Disabled

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MASTER_TODM_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TODM_Disabled.TODM_Disabled_C
// 0x0010 (0x12F0 - 0x12E0)
class ATODM_Disabled_C final : public AMASTER_TODM_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_TODM_Disabled_C;                    // 0x12E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void Update_Scalabilty_Settings();
	void ExecuteUbergraph_TODM_Disabled(int32 EntryPoint);
	void SetReflectionQualityMPC();
	void DisableLightAndFog(bool Enable);
	void SetGlobalIlluminationMPC();
	void DebugScalabilitySettings();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TODM_Disabled_C">();
	}
	static class ATODM_Disabled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATODM_Disabled_C>();
	}
};

}

